# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BINARY_7Z "OFF")
set(CPACK_BINARY_IFW "OFF")
set(CPACK_BINARY_INNOSETUP "OFF")
set(CPACK_BINARY_NSIS "ON")
set(CPACK_BINARY_NUGET "OFF")
set(CPACK_BINARY_WIX "OFF")
set(CPACK_BINARY_ZIP "OFF")
set(CPACK_BUILD_SOURCE_DIRS "F:/prc_v1_d2026_04_24/prc_v0.1.05 (1)/prc_v0.1.05_d2013_04_30;F:/prc_v1_d2026_04_24/test/legacy_prc_build")
set(CPACK_CMAKE_GENERATOR "MinGW Makefiles")
set(CPACK_COMPONENTS_ALL "")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "D:/MiKTeX/strawberry-perl-5.42.2.1-64bit-portable/c/share/cmake-3.29/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "PRC built using CMake")
set(CPACK_GENERATOR "NSIS")
set(CPACK_INSTALL_CMAKE_PROJECTS "F:/prc_v1_d2026_04_24/test/legacy_prc_build;PRC;ALL;/")
set(CPACK_INSTALL_PREFIX "C:/Program Files (x86)/PRC")
set(CPACK_MODULE_PATH "")
set(CPACK_NSIS_DISPLAY_NAME "PRC 0.1.1")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_PACKAGE_NAME "PRC 0.1.1")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OBJCOPY_EXECUTABLE "D:/MiKTeX/strawberry-perl-5.42.2.1-64bit-portable/c/bin/objcopy.exe")
set(CPACK_OBJDUMP_EXECUTABLE "D:/MiKTeX/strawberry-perl-5.42.2.1-64bit-portable/c/bin/objdump.exe")
set(CPACK_OUTPUT_CONFIG_FILE "F:/prc_v1_d2026_04_24/test/legacy_prc_build/CPackConfig.cmake")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "D:/MiKTeX/strawberry-perl-5.42.2.1-64bit-portable/c/share/cmake-3.29/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "PRC built using CMake")
set(CPACK_PACKAGE_FILE_NAME "PRC-0.1.1-")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "PRC 0.1.1")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "PRC 0.1.1")
set(CPACK_PACKAGE_NAME "PRC")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "Humanity")
set(CPACK_PACKAGE_VERSION "0.1.1")
set(CPACK_PACKAGE_VERSION_MAJOR "0")
set(CPACK_PACKAGE_VERSION_MINOR "1")
set(CPACK_PACKAGE_VERSION_PATCH "1")
set(CPACK_READELF_EXECUTABLE "D:/MiKTeX/strawberry-perl-5.42.2.1-64bit-portable/c/bin/readelf.exe")
set(CPACK_RESOURCE_FILE_LICENSE "D:/MiKTeX/strawberry-perl-5.42.2.1-64bit-portable/c/share/cmake-3.29/Templates/CPack.GenericLicense.txt")
set(CPACK_RESOURCE_FILE_README "D:/MiKTeX/strawberry-perl-5.42.2.1-64bit-portable/c/share/cmake-3.29/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "D:/MiKTeX/strawberry-perl-5.42.2.1-64bit-portable/c/share/cmake-3.29/Templates/CPack.GenericWelcome.txt")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_7Z "ON")
set(CPACK_SOURCE_GENERATOR "7Z;ZIP")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "F:/prc_v1_d2026_04_24/test/legacy_prc_build/CPackSourceConfig.cmake")
set(CPACK_SOURCE_ZIP "ON")
set(CPACK_SYSTEM_NAME "")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "")
set(CPACK_WIX_SIZEOF_VOID_P "")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "F:/prc_v1_d2026_04_24/test/legacy_prc_build/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
