/* This file was generated by PyBindGen 0.16.0 */
#define PY_SSIZE_T_CLEAN
#include <Python.h>
#include <stddef.h>


#if PY_VERSION_HEX < 0x020400F0

#define PyEval_ThreadsInitialized() 1

#define Py_CLEAR(op)				\
        do {                            	\
                if (op) {			\
                        PyObject *tmp = (PyObject *)(op);	\
                        (op) = NULL;		\
                        Py_DECREF(tmp);		\
                }				\
        } while (0)


#define Py_VISIT(op)							\
        do { 								\
                if (op) {						\
                        int vret = visit((PyObject *)(op), arg);	\
                        if (vret)					\
                                return vret;				\
                }							\
        } while (0)

#endif



#if PY_VERSION_HEX < 0x020500F0

typedef int Py_ssize_t;
# define PY_SSIZE_T_MAX INT_MAX
# define PY_SSIZE_T_MIN INT_MIN
typedef inquiry lenfunc;
typedef intargfunc ssizeargfunc;
typedef intobjargproc ssizeobjargproc;

#endif


#if     __GNUC__ > 2
# define PYBINDGEN_UNUSED(param) param __attribute__((__unused__))
#elif     __GNUC__ > 2 || (__GNUC__ == 2 && __GNUC_MINOR__ > 4)
# define PYBINDGEN_UNUSED(param) __attribute__((__unused__)) param
#else
# define PYBINDGEN_UNUSED(param) param
#endif  /* !__GNUC__ */

typedef enum _PyBindGenWrapperFlags {
   PYBINDGEN_WRAPPER_FLAG_NONE = 0,
   PYBINDGEN_WRAPPER_FLAG_OBJECT_NOT_OWNED = (1<<0),
} PyBindGenWrapperFlags;


#include "prc/FlatStruct.h"
#include "prc/prcCountsStruct.h"
#include <stdio.h>
#include <map>
#include <iostream>
/* --- forward declarations --- */


typedef struct {
    PyObject_HEAD
    FILE *obj;
    PyBindGenWrapperFlags flags:8;
} PyFILE;


extern PyTypeObject *_PyFILE_Type;
#define PyFILE_Type (*_PyFILE_Type)

extern std::map<void*, PyObject*> *_PyFILE_wrapper_registry;
#define PyFILE_wrapper_registry (*_PyFILE_wrapper_registry)

extern PyTypeObject *Pystd__exception_Type;

/* --- forward declarations --- */


typedef struct {
    PyObject_HEAD
    PRC::FlatStruct *obj;
    PyBindGenWrapperFlags flags:8;
} PyPRCFlatStruct;


extern PyTypeObject PyPRCFlatStruct_Type;

extern std::map<void*, PyObject*> PyPRCFlatStruct_wrapper_registry;

typedef struct {
    PyObject_HEAD
    PRC::prcCountsStruct *obj;
    PyBindGenWrapperFlags flags:8;
} PyPRCPrcCountsStruct;


extern PyTypeObject PyPRCPrcCountsStruct_Type;

extern std::map<void*, PyObject*> PyPRCPrcCountsStruct_wrapper_registry;
/* --- module functions --- */


PyObject *
_wrap_prc_impl_PRC_biff(PyObject * PYBINDGEN_UNUSED(dummy), PyObject *args, PyObject *kwargs)
{
    PyObject *py_retval;
    int retval;
    PyPRCFlatStruct *fs;
    const char *keywords[] = {"fs", NULL};

    if (!PyArg_ParseTupleAndKeywords(args, kwargs, (char *) "O!", (char **) keywords, &PyPRCFlatStruct_Type, &fs)) {
        return NULL;
    }
    retval = PRC::biff(*((PyPRCFlatStruct *) fs)->obj);
    py_retval = Py_BuildValue((char *) "i", retval);
    return py_retval;
}
PyObject * _wrap_prc_impl_PRC_biff(PyObject * PYBINDGEN_UNUSED(dummy), PyObject *args, PyObject *kwargs);

static PyMethodDef prc_impl_PRC_functions[] = {
    {(char *) "biff", (PyCFunction) _wrap_prc_impl_PRC_biff, METH_KEYWORDS|METH_VARARGS, NULL },
    {NULL, NULL, 0, NULL}
};
/* --- classes --- */


std::map<void*, PyObject*> PyPRCFlatStruct_wrapper_registry;
static PyObject* _wrap_PyPRCFlatStruct__get_start(PyPRCFlatStruct *self, void * PYBINDGEN_UNUSED(closure))
{
    PyObject *py_retval;

    py_retval = Py_BuildValue((char *) "i", self->obj->start);
    return py_retval;
}
static int _wrap_PyPRCFlatStruct__set_start(PyPRCFlatStruct *self, PyObject *value, void * PYBINDGEN_UNUSED(closure))
{
    PyObject *py_retval;

    py_retval = Py_BuildValue((char *) "(O)", value);
    if (!PyArg_ParseTuple(py_retval, (char *) "i", &self->obj->start)) {
        Py_DECREF(py_retval);
        return -1;
    }
    Py_DECREF(py_retval);
    return 0;
}
static PyObject* _wrap_PyPRCFlatStruct__get_stop(PyPRCFlatStruct *self, void * PYBINDGEN_UNUSED(closure))
{
    PyObject *py_retval;

    py_retval = Py_BuildValue((char *) "i", self->obj->stop);
    return py_retval;
}
static int _wrap_PyPRCFlatStruct__set_stop(PyPRCFlatStruct *self, PyObject *value, void * PYBINDGEN_UNUSED(closure))
{
    PyObject *py_retval;

    py_retval = Py_BuildValue((char *) "(O)", value);
    if (!PyArg_ParseTuple(py_retval, (char *) "i", &self->obj->stop)) {
        Py_DECREF(py_retval);
        return -1;
    }
    Py_DECREF(py_retval);
    return 0;
}
static PyObject* _wrap_PyPRCFlatStruct__get_type(PyPRCFlatStruct *self, void * PYBINDGEN_UNUSED(closure))
{
    PyObject *py_retval;

    py_retval = Py_BuildValue((char *) "i", self->obj->type);
    return py_retval;
}
static int _wrap_PyPRCFlatStruct__set_type(PyPRCFlatStruct *self, PyObject *value, void * PYBINDGEN_UNUSED(closure))
{
    PyObject *py_retval;

    py_retval = Py_BuildValue((char *) "(O)", value);
    if (!PyArg_ParseTuple(py_retval, (char *) "i", &self->obj->type)) {
        Py_DECREF(py_retval);
        return -1;
    }
    Py_DECREF(py_retval);
    return 0;
}
static PyGetSetDef PyPRCFlatStruct__getsets[] = {
    {
        (char*) "start", /* attribute name */
        (getter) _wrap_PyPRCFlatStruct__get_start, /* C function to get the attribute */
        (setter) _wrap_PyPRCFlatStruct__set_start, /* C function to set the attribute */
        NULL, /* optional doc string */
        NULL /* optional additional data for getter and setter */
    },
    {
        (char*) "stop", /* attribute name */
        (getter) _wrap_PyPRCFlatStruct__get_stop, /* C function to get the attribute */
        (setter) _wrap_PyPRCFlatStruct__set_stop, /* C function to set the attribute */
        NULL, /* optional doc string */
        NULL /* optional additional data for getter and setter */
    },
    {
        (char*) "type", /* attribute name */
        (getter) _wrap_PyPRCFlatStruct__get_type, /* C function to get the attribute */
        (setter) _wrap_PyPRCFlatStruct__set_type, /* C function to set the attribute */
        NULL, /* optional doc string */
        NULL /* optional additional data for getter and setter */
    },
    { NULL, NULL, NULL, NULL, NULL }
};


static int
_wrap_PyPRCFlatStruct__tp_init__0(PyPRCFlatStruct *self, PyObject *args, PyObject *kwargs, PyObject **return_exception)
{
    PyPRCFlatStruct *arg0;
    const char *keywords[] = {"arg0", NULL};

    if (!PyArg_ParseTupleAndKeywords(args, kwargs, (char *) "O!", (char **) keywords, &PyPRCFlatStruct_Type, &arg0)) {
        {
            PyObject *exc_type, *traceback;
            PyErr_Fetch(&exc_type, return_exception, &traceback);
            Py_XDECREF(exc_type);
            Py_XDECREF(traceback);
        }
        return -1;
    }
    self->obj = new PRC::FlatStruct(*((PyPRCFlatStruct *) arg0)->obj);
    self->flags = PYBINDGEN_WRAPPER_FLAG_NONE;
    return 0;
}

static int
_wrap_PyPRCFlatStruct__tp_init__1(PyPRCFlatStruct *self, PyObject *args, PyObject *kwargs, PyObject **return_exception)
{
    const char *keywords[] = {NULL};

    if (!PyArg_ParseTupleAndKeywords(args, kwargs, (char *) "", (char **) keywords)) {
        {
            PyObject *exc_type, *traceback;
            PyErr_Fetch(&exc_type, return_exception, &traceback);
            Py_XDECREF(exc_type);
            Py_XDECREF(traceback);
        }
        return -1;
    }
    self->obj = new PRC::FlatStruct();
    self->flags = PYBINDGEN_WRAPPER_FLAG_NONE;
    return 0;
}

static int
_wrap_PyPRCFlatStruct__tp_init__2(PyPRCFlatStruct *self, PyObject *args, PyObject *kwargs, PyObject **return_exception)
{
    int begin;
    int end;
    PRC::FlatStruct::FlatType t;
    const char *keywords[] = {"begin", "end", "t", NULL};

    if (!PyArg_ParseTupleAndKeywords(args, kwargs, (char *) "iii", (char **) keywords, &begin, &end, &t)) {
        {
            PyObject *exc_type, *traceback;
            PyErr_Fetch(&exc_type, return_exception, &traceback);
            Py_XDECREF(exc_type);
            Py_XDECREF(traceback);
        }
        return -1;
    }
    self->obj = new PRC::FlatStruct(begin, end, t);
    self->flags = PYBINDGEN_WRAPPER_FLAG_NONE;
    return 0;
}

int _wrap_PyPRCFlatStruct__tp_init(PyPRCFlatStruct *self, PyObject *args, PyObject *kwargs)
{
    int retval;
    PyObject *error_list;
    PyObject *exceptions[3] = {0,};
    retval = _wrap_PyPRCFlatStruct__tp_init__0(self, args, kwargs, &exceptions[0]);
    if (!exceptions[0]) {
        return retval;
    }
    retval = _wrap_PyPRCFlatStruct__tp_init__1(self, args, kwargs, &exceptions[1]);
    if (!exceptions[1]) {
        Py_DECREF(exceptions[0]);
        return retval;
    }
    retval = _wrap_PyPRCFlatStruct__tp_init__2(self, args, kwargs, &exceptions[2]);
    if (!exceptions[2]) {
        Py_DECREF(exceptions[0]);
        Py_DECREF(exceptions[1]);
        return retval;
    }
    error_list = PyList_New(3);
    PyList_SET_ITEM(error_list, 0, PyObject_Str(exceptions[0]));
    Py_DECREF(exceptions[0]);
    PyList_SET_ITEM(error_list, 1, PyObject_Str(exceptions[1]));
    Py_DECREF(exceptions[1]);
    PyList_SET_ITEM(error_list, 2, PyObject_Str(exceptions[2]));
    Py_DECREF(exceptions[2]);
    PyErr_SetObject(PyExc_TypeError, error_list);
    Py_DECREF(error_list);
    return -1;
}


PyObject *
_wrap_PyPRCFlatStruct_Print(PyPRCFlatStruct *self)
{
    PyObject *py_retval;
    std::string retval;

    retval = self->obj->Print();
    py_retval = Py_BuildValue((char *) "s#", (retval).c_str(), (retval).size());
    return py_retval;
}


static PyObject*
_wrap_PyPRCFlatStruct__copy__(PyPRCFlatStruct *self)
{

    PyPRCFlatStruct *py_copy;
    py_copy = PyObject_New(PyPRCFlatStruct, &PyPRCFlatStruct_Type);
    py_copy->obj = new PRC::FlatStruct(*self->obj);
    py_copy->flags = PYBINDGEN_WRAPPER_FLAG_NONE;
    PyPRCFlatStruct_wrapper_registry[(void *) py_copy->obj] = (PyObject *) py_copy;
    return (PyObject*) py_copy;
}

static PyMethodDef PyPRCFlatStruct_methods[] = {
    {(char *) "Print", (PyCFunction) _wrap_PyPRCFlatStruct_Print, METH_NOARGS, NULL },
    {(char *) "__copy__", (PyCFunction) _wrap_PyPRCFlatStruct__copy__, METH_NOARGS, NULL},
    {NULL, NULL, 0, NULL}
};

static void
_wrap_PyPRCFlatStruct__tp_dealloc(PyPRCFlatStruct *self)
{
    std::map<void*, PyObject*>::iterator wrapper_lookup_iter;
    wrapper_lookup_iter = PyPRCFlatStruct_wrapper_registry.find((void *) self->obj);
    if (wrapper_lookup_iter != PyPRCFlatStruct_wrapper_registry.end()) {
        PyPRCFlatStruct_wrapper_registry.erase(wrapper_lookup_iter);
    }

        PRC::FlatStruct *tmp = self->obj;
        self->obj = NULL;
        if (!(self->flags&PYBINDGEN_WRAPPER_FLAG_OBJECT_NOT_OWNED)) {
            delete tmp;
        }
    self->ob_type->tp_free((PyObject*)self);
}

static PyObject*
_wrap_PyPRCFlatStruct__tp_richcompare (PyPRCFlatStruct *PYBINDGEN_UNUSED(self), PyPRCFlatStruct *other, int opid)
{

    if (!PyObject_IsInstance((PyObject*) other, (PyObject*) &PyPRCFlatStruct_Type)) {
        Py_INCREF(Py_NotImplemented);
        return Py_NotImplemented;
    }
    switch (opid)
    {
    case Py_LT:
        Py_INCREF(Py_NotImplemented);
        return Py_NotImplemented;
    case Py_LE:
        Py_INCREF(Py_NotImplemented);
        return Py_NotImplemented;
    case Py_EQ:
        Py_INCREF(Py_NotImplemented);
        return Py_NotImplemented;
    case Py_NE:
        Py_INCREF(Py_NotImplemented);
        return Py_NotImplemented;
    case Py_GE:
        Py_INCREF(Py_NotImplemented);
        return Py_NotImplemented;
    case Py_GT:
        Py_INCREF(Py_NotImplemented);
        return Py_NotImplemented;
    } /* closes switch (opid) */
    Py_INCREF(Py_NotImplemented);
    return Py_NotImplemented;
}

PyTypeObject PyPRCFlatStruct_Type = {
    PyObject_HEAD_INIT(NULL)
    0,                                 /* ob_size */
    (char *) "prc_impl.PRC.FlatStruct",            /* tp_name */
    sizeof(PyPRCFlatStruct),                  /* tp_basicsize */
    0,                                 /* tp_itemsize */
    /* methods */
    (destructor)_wrap_PyPRCFlatStruct__tp_dealloc,        /* tp_dealloc */
    (printfunc)0,                      /* tp_print */
    (getattrfunc)NULL,       /* tp_getattr */
    (setattrfunc)NULL,       /* tp_setattr */
    (cmpfunc)NULL,           /* tp_compare */
    (reprfunc)NULL,             /* tp_repr */
    (PyNumberMethods*)NULL,     /* tp_as_number */
    (PySequenceMethods*)NULL, /* tp_as_sequence */
    (PyMappingMethods*)NULL,   /* tp_as_mapping */
    (hashfunc)NULL,             /* tp_hash */
    (ternaryfunc)NULL,          /* tp_call */
    (reprfunc)NULL,              /* tp_str */
    (getattrofunc)NULL,     /* tp_getattro */
    (setattrofunc)NULL,     /* tp_setattro */
    (PyBufferProcs*)NULL,  /* tp_as_buffer */
    Py_TPFLAGS_DEFAULT,                      /* tp_flags */
    NULL,                        /* Documentation string */
    (traverseproc)NULL,     /* tp_traverse */
    (inquiry)NULL,             /* tp_clear */
    (richcmpfunc)_wrap_PyPRCFlatStruct__tp_richcompare,   /* tp_richcompare */
    0,             /* tp_weaklistoffset */
    (getiterfunc)NULL,          /* tp_iter */
    (iternextfunc)NULL,     /* tp_iternext */
    (struct PyMethodDef*)PyPRCFlatStruct_methods, /* tp_methods */
    (struct PyMemberDef*)0,              /* tp_members */
    PyPRCFlatStruct__getsets,                     /* tp_getset */
    NULL,                              /* tp_base */
    NULL,                              /* tp_dict */
    (descrgetfunc)NULL,    /* tp_descr_get */
    (descrsetfunc)NULL,    /* tp_descr_set */
    0,                 /* tp_dictoffset */
    (initproc)_wrap_PyPRCFlatStruct__tp_init,             /* tp_init */
    (allocfunc)PyType_GenericAlloc,           /* tp_alloc */
    (newfunc)PyType_GenericNew,               /* tp_new */
    (freefunc)0,             /* tp_free */
    (inquiry)NULL,             /* tp_is_gc */
    NULL,                              /* tp_bases */
    NULL,                              /* tp_mro */
    NULL,                              /* tp_cache */
    NULL,                              /* tp_subclasses */
    NULL,                              /* tp_weaklist */
    (destructor) NULL                  /* tp_del */
};



std::map<void*, PyObject*> PyPRCPrcCountsStruct_wrapper_registry;
static PyObject* _wrap_PyPRCPrcCountsStruct__get_numberOfInversions(PyPRCPrcCountsStruct *self, void * PYBINDGEN_UNUSED(closure))
{
    PyObject *py_retval;

    py_retval = Py_BuildValue((char *) "l", self->obj->numberOfInversions);
    return py_retval;
}
static int _wrap_PyPRCPrcCountsStruct__set_numberOfInversions(PyPRCPrcCountsStruct *self, PyObject *value, void * PYBINDGEN_UNUSED(closure))
{
    PyObject *py_retval;

    py_retval = Py_BuildValue((char *) "(O)", value);
    if (!PyArg_ParseTuple(py_retval, (char *) "l", &self->obj->numberOfInversions)) {
        Py_DECREF(py_retval);
        return -1;
    }
    Py_DECREF(py_retval);
    return 0;
}
static PyObject* _wrap_PyPRCPrcCountsStruct__get_numberOfIterations(PyPRCPrcCountsStruct *self, void * PYBINDGEN_UNUSED(closure))
{
    PyObject *py_retval;

    py_retval = Py_BuildValue((char *) "l", self->obj->numberOfIterations);
    return py_retval;
}
static int _wrap_PyPRCPrcCountsStruct__set_numberOfIterations(PyPRCPrcCountsStruct *self, PyObject *value, void * PYBINDGEN_UNUSED(closure))
{
    PyObject *py_retval;

    py_retval = Py_BuildValue((char *) "(O)", value);
    if (!PyArg_ParseTuple(py_retval, (char *) "l", &self->obj->numberOfIterations)) {
        Py_DECREF(py_retval);
        return -1;
    }
    Py_DECREF(py_retval);
    return 0;
}
static PyObject* _wrap_PyPRCPrcCountsStruct__get_numberOfShifts(PyPRCPrcCountsStruct *self, void * PYBINDGEN_UNUSED(closure))
{
    PyObject *py_retval;

    py_retval = Py_BuildValue((char *) "l", self->obj->numberOfShifts);
    return py_retval;
}
static int _wrap_PyPRCPrcCountsStruct__set_numberOfShifts(PyPRCPrcCountsStruct *self, PyObject *value, void * PYBINDGEN_UNUSED(closure))
{
    PyObject *py_retval;

    py_retval = Py_BuildValue((char *) "(O)", value);
    if (!PyArg_ParseTuple(py_retval, (char *) "l", &self->obj->numberOfShifts)) {
        Py_DECREF(py_retval);
        return -1;
    }
    Py_DECREF(py_retval);
    return 0;
}
static PyGetSetDef PyPRCPrcCountsStruct__getsets[] = {
    {
        (char*) "numberOfIterations", /* attribute name */
        (getter) _wrap_PyPRCPrcCountsStruct__get_numberOfIterations, /* C function to get the attribute */
        (setter) _wrap_PyPRCPrcCountsStruct__set_numberOfIterations, /* C function to set the attribute */
        NULL, /* optional doc string */
        NULL /* optional additional data for getter and setter */
    },
    {
        (char*) "numberOfInversions", /* attribute name */
        (getter) _wrap_PyPRCPrcCountsStruct__get_numberOfInversions, /* C function to get the attribute */
        (setter) _wrap_PyPRCPrcCountsStruct__set_numberOfInversions, /* C function to set the attribute */
        NULL, /* optional doc string */
        NULL /* optional additional data for getter and setter */
    },
    {
        (char*) "numberOfShifts", /* attribute name */
        (getter) _wrap_PyPRCPrcCountsStruct__get_numberOfShifts, /* C function to get the attribute */
        (setter) _wrap_PyPRCPrcCountsStruct__set_numberOfShifts, /* C function to set the attribute */
        NULL, /* optional doc string */
        NULL /* optional additional data for getter and setter */
    },
    { NULL, NULL, NULL, NULL, NULL }
};


static int
_wrap_PyPRCPrcCountsStruct__tp_init__0(PyPRCPrcCountsStruct *self, PyObject *args, PyObject *kwargs, PyObject **return_exception)
{
    PyPRCPrcCountsStruct *arg0;
    const char *keywords[] = {"arg0", NULL};

    if (!PyArg_ParseTupleAndKeywords(args, kwargs, (char *) "O!", (char **) keywords, &PyPRCPrcCountsStruct_Type, &arg0)) {
        {
            PyObject *exc_type, *traceback;
            PyErr_Fetch(&exc_type, return_exception, &traceback);
            Py_XDECREF(exc_type);
            Py_XDECREF(traceback);
        }
        return -1;
    }
    self->obj = new PRC::prcCountsStruct(*((PyPRCPrcCountsStruct *) arg0)->obj);
    self->flags = PYBINDGEN_WRAPPER_FLAG_NONE;
    return 0;
}

static int
_wrap_PyPRCPrcCountsStruct__tp_init__1(PyPRCPrcCountsStruct *self, PyObject *args, PyObject *kwargs, PyObject **return_exception)
{
    const char *keywords[] = {NULL};

    if (!PyArg_ParseTupleAndKeywords(args, kwargs, (char *) "", (char **) keywords)) {
        {
            PyObject *exc_type, *traceback;
            PyErr_Fetch(&exc_type, return_exception, &traceback);
            Py_XDECREF(exc_type);
            Py_XDECREF(traceback);
        }
        return -1;
    }
    self->obj = new PRC::prcCountsStruct();
    self->flags = PYBINDGEN_WRAPPER_FLAG_NONE;
    return 0;
}

static int
_wrap_PyPRCPrcCountsStruct__tp_init__2(PyPRCPrcCountsStruct *self, PyObject *args, PyObject *kwargs, PyObject **return_exception)
{
    long int shifts;
    long int inversions;
    long int iterations;
    const char *keywords[] = {"shifts", "inversions", "iterations", NULL};

    if (!PyArg_ParseTupleAndKeywords(args, kwargs, (char *) "lll", (char **) keywords, &shifts, &inversions, &iterations)) {
        {
            PyObject *exc_type, *traceback;
            PyErr_Fetch(&exc_type, return_exception, &traceback);
            Py_XDECREF(exc_type);
            Py_XDECREF(traceback);
        }
        return -1;
    }
    self->obj = new PRC::prcCountsStruct(shifts, inversions, iterations);
    self->flags = PYBINDGEN_WRAPPER_FLAG_NONE;
    return 0;
}

int _wrap_PyPRCPrcCountsStruct__tp_init(PyPRCPrcCountsStruct *self, PyObject *args, PyObject *kwargs)
{
    int retval;
    PyObject *error_list;
    PyObject *exceptions[3] = {0,};
    retval = _wrap_PyPRCPrcCountsStruct__tp_init__0(self, args, kwargs, &exceptions[0]);
    if (!exceptions[0]) {
        return retval;
    }
    retval = _wrap_PyPRCPrcCountsStruct__tp_init__1(self, args, kwargs, &exceptions[1]);
    if (!exceptions[1]) {
        Py_DECREF(exceptions[0]);
        return retval;
    }
    retval = _wrap_PyPRCPrcCountsStruct__tp_init__2(self, args, kwargs, &exceptions[2]);
    if (!exceptions[2]) {
        Py_DECREF(exceptions[0]);
        Py_DECREF(exceptions[1]);
        return retval;
    }
    error_list = PyList_New(3);
    PyList_SET_ITEM(error_list, 0, PyObject_Str(exceptions[0]));
    Py_DECREF(exceptions[0]);
    PyList_SET_ITEM(error_list, 1, PyObject_Str(exceptions[1]));
    Py_DECREF(exceptions[1]);
    PyList_SET_ITEM(error_list, 2, PyObject_Str(exceptions[2]));
    Py_DECREF(exceptions[2]);
    PyErr_SetObject(PyExc_TypeError, error_list);
    Py_DECREF(error_list);
    return -1;
}


PyObject *
_wrap_PyPRCPrcCountsStruct_Print(PyPRCPrcCountsStruct *self, PyObject *args, PyObject *kwargs)
{
    PyObject *py_retval;
    std::string retval;
    char const *indent = "";
    char const *sep = "\012";
    const char *keywords[] = {"indent", "sep", NULL};

    if (!PyArg_ParseTupleAndKeywords(args, kwargs, (char *) "|ss", (char **) keywords, &indent, &sep)) {
        return NULL;
    }
    retval = self->obj->Print(indent, sep);
    py_retval = Py_BuildValue((char *) "s#", (retval).c_str(), (retval).size());
    return py_retval;
}


static PyObject*
_wrap_PyPRCPrcCountsStruct__copy__(PyPRCPrcCountsStruct *self)
{

    PyPRCPrcCountsStruct *py_copy;
    py_copy = PyObject_New(PyPRCPrcCountsStruct, &PyPRCPrcCountsStruct_Type);
    py_copy->obj = new PRC::prcCountsStruct(*self->obj);
    py_copy->flags = PYBINDGEN_WRAPPER_FLAG_NONE;
    PyPRCPrcCountsStruct_wrapper_registry[(void *) py_copy->obj] = (PyObject *) py_copy;
    return (PyObject*) py_copy;
}

static PyMethodDef PyPRCPrcCountsStruct_methods[] = {
    {(char *) "Print", (PyCFunction) _wrap_PyPRCPrcCountsStruct_Print, METH_KEYWORDS|METH_VARARGS, NULL },
    {(char *) "__copy__", (PyCFunction) _wrap_PyPRCPrcCountsStruct__copy__, METH_NOARGS, NULL},
    {NULL, NULL, 0, NULL}
};

static void
_wrap_PyPRCPrcCountsStruct__tp_dealloc(PyPRCPrcCountsStruct *self)
{
    std::map<void*, PyObject*>::iterator wrapper_lookup_iter;
    wrapper_lookup_iter = PyPRCPrcCountsStruct_wrapper_registry.find((void *) self->obj);
    if (wrapper_lookup_iter != PyPRCPrcCountsStruct_wrapper_registry.end()) {
        PyPRCPrcCountsStruct_wrapper_registry.erase(wrapper_lookup_iter);
    }

        PRC::prcCountsStruct *tmp = self->obj;
        self->obj = NULL;
        if (!(self->flags&PYBINDGEN_WRAPPER_FLAG_OBJECT_NOT_OWNED)) {
            delete tmp;
        }
    self->ob_type->tp_free((PyObject*)self);
}

static PyObject*
_wrap_PyPRCPrcCountsStruct__tp_richcompare (PyPRCPrcCountsStruct *PYBINDGEN_UNUSED(self), PyPRCPrcCountsStruct *other, int opid)
{

    if (!PyObject_IsInstance((PyObject*) other, (PyObject*) &PyPRCPrcCountsStruct_Type)) {
        Py_INCREF(Py_NotImplemented);
        return Py_NotImplemented;
    }
    switch (opid)
    {
    case Py_LT:
        Py_INCREF(Py_NotImplemented);
        return Py_NotImplemented;
    case Py_LE:
        Py_INCREF(Py_NotImplemented);
        return Py_NotImplemented;
    case Py_EQ:
        Py_INCREF(Py_NotImplemented);
        return Py_NotImplemented;
    case Py_NE:
        Py_INCREF(Py_NotImplemented);
        return Py_NotImplemented;
    case Py_GE:
        Py_INCREF(Py_NotImplemented);
        return Py_NotImplemented;
    case Py_GT:
        Py_INCREF(Py_NotImplemented);
        return Py_NotImplemented;
    } /* closes switch (opid) */
    Py_INCREF(Py_NotImplemented);
    return Py_NotImplemented;
}

PyTypeObject PyPRCPrcCountsStruct_Type = {
    PyObject_HEAD_INIT(NULL)
    0,                                 /* ob_size */
    (char *) "prc_impl.PRC.PrcCountsStruct",            /* tp_name */
    sizeof(PyPRCPrcCountsStruct),                  /* tp_basicsize */
    0,                                 /* tp_itemsize */
    /* methods */
    (destructor)_wrap_PyPRCPrcCountsStruct__tp_dealloc,        /* tp_dealloc */
    (printfunc)0,                      /* tp_print */
    (getattrfunc)NULL,       /* tp_getattr */
    (setattrfunc)NULL,       /* tp_setattr */
    (cmpfunc)NULL,           /* tp_compare */
    (reprfunc)NULL,             /* tp_repr */
    (PyNumberMethods*)NULL,     /* tp_as_number */
    (PySequenceMethods*)NULL, /* tp_as_sequence */
    (PyMappingMethods*)NULL,   /* tp_as_mapping */
    (hashfunc)NULL,             /* tp_hash */
    (ternaryfunc)NULL,          /* tp_call */
    (reprfunc)NULL,              /* tp_str */
    (getattrofunc)NULL,     /* tp_getattro */
    (setattrofunc)NULL,     /* tp_setattro */
    (PyBufferProcs*)NULL,  /* tp_as_buffer */
    Py_TPFLAGS_DEFAULT,                      /* tp_flags */
    NULL,                        /* Documentation string */
    (traverseproc)NULL,     /* tp_traverse */
    (inquiry)NULL,             /* tp_clear */
    (richcmpfunc)_wrap_PyPRCPrcCountsStruct__tp_richcompare,   /* tp_richcompare */
    0,             /* tp_weaklistoffset */
    (getiterfunc)NULL,          /* tp_iter */
    (iternextfunc)NULL,     /* tp_iternext */
    (struct PyMethodDef*)PyPRCPrcCountsStruct_methods, /* tp_methods */
    (struct PyMemberDef*)0,              /* tp_members */
    PyPRCPrcCountsStruct__getsets,                     /* tp_getset */
    NULL,                              /* tp_base */
    NULL,                              /* tp_dict */
    (descrgetfunc)NULL,    /* tp_descr_get */
    (descrsetfunc)NULL,    /* tp_descr_set */
    0,                 /* tp_dictoffset */
    (initproc)_wrap_PyPRCPrcCountsStruct__tp_init,             /* tp_init */
    (allocfunc)PyType_GenericAlloc,           /* tp_alloc */
    (newfunc)PyType_GenericNew,               /* tp_new */
    (freefunc)0,             /* tp_free */
    (inquiry)NULL,             /* tp_is_gc */
    NULL,                              /* tp_bases */
    NULL,                              /* tp_mro */
    NULL,                              /* tp_cache */
    NULL,                              /* tp_subclasses */
    NULL,                              /* tp_weaklist */
    (destructor) NULL                  /* tp_del */
};


/* --- enumerations --- */




static PyObject *
initprc_impl_PRC(void)
{
    PyObject *m;
    m = Py_InitModule3((char *) "prc_impl.PRC", prc_impl_PRC_functions, NULL);
    if (m == NULL) {
        return NULL;
    }
    PyModule_AddObject(m, (char *) "_PyPRCFlatStruct_wrapper_registry", PyCObject_FromVoidPtr(&PyPRCFlatStruct_wrapper_registry, NULL));
    /* Register the 'PRC::FlatStruct' class */
    if (PyType_Ready(&PyPRCFlatStruct_Type)) {
        return NULL;
    }
    PyModule_AddObject(m, (char *) "FlatStruct", (PyObject *) &PyPRCFlatStruct_Type);
    PyModule_AddObject(m, (char *) "_PyPRCPrcCountsStruct_wrapper_registry", PyCObject_FromVoidPtr(&PyPRCPrcCountsStruct_wrapper_registry, NULL));
    /* Register the 'PRC::prcCountsStruct' class */
    if (PyType_Ready(&PyPRCPrcCountsStruct_Type)) {
        return NULL;
    }
    PyModule_AddObject(m, (char *) "prcCountsStruct", (PyObject *) &PyPRCPrcCountsStruct_Type);
    {
        PyObject *tmp_value;
         // PRC::FlatStruct::LocalMin
        tmp_value = PyInt_FromLong(PRC::FlatStruct::LocalMin);
        PyDict_SetItemString((PyObject*) PyPRCFlatStruct_Type.tp_dict, "LocalMin", tmp_value);
        Py_DECREF(tmp_value);
         // PRC::FlatStruct::LocalMax
        tmp_value = PyInt_FromLong(PRC::FlatStruct::LocalMax);
        PyDict_SetItemString((PyObject*) PyPRCFlatStruct_Type.tp_dict, "LocalMax", tmp_value);
        Py_DECREF(tmp_value);
    }
    return m;
}
static PyMethodDef prc_impl_std_functions[] = {
    {NULL, NULL, 0, NULL}
};

static PyObject *
initprc_impl_std(void)
{
    PyObject *m;
    m = Py_InitModule3((char *) "prc_impl.std", prc_impl_std_functions, NULL);
    if (m == NULL) {
        return NULL;
    }
    return m;
}
/* --- module functions --- */




static PyObject *
_wrap_foofunction_that_takes_foo_from_string(PyObject * PYBINDGEN_UNUSED(dummy), PyObject *args,
                                             PyObject *kwargs, PyObject **return_exception)
{
    PyObject *py_retval;
    char *datum;
    const char *keywords[] = {"foo", NULL};

    if (!PyArg_ParseTupleAndKeywords(args, kwargs, (char *) "s", (char **) keywords, &datum)) {
        {
            PyObject *exc_type, *traceback;
            PyErr_Fetch(&exc_type, return_exception, &traceback);
            Py_XDECREF(exc_type);
            Py_XDECREF(traceback);
        }
        return NULL;
    }
    function_that_takes_foo(Foo(datum));
    Py_INCREF(Py_None);
    py_retval = Py_None;
    return py_retval;
}


PyObject * _wrap_prc_impl_function_that_takes_foo(PyObject *self, PyObject *args, PyObject *kwargs)
{
    PyObject * retval;
    PyObject *error_list;
    PyObject *exceptions[1] = {0,};
    retval = _wrap_foofunction_that_takes_foo_from_string(self, args, kwargs, &exceptions[0]);
    if (!exceptions[0]) {
        return retval;
    }
    error_list = PyList_New(1);
    PyList_SET_ITEM(error_list, 0, PyObject_Str(exceptions[0]));
    Py_DECREF(exceptions[0]);
    PyErr_SetObject(PyExc_TypeError, error_list);
    Py_DECREF(error_list);
    return NULL;
}
PyObject * _wrap_prc_impl_function_that_takes_foo(PyObject *self, PyObject *args, PyObject *kwargs);

static PyMethodDef prc_impl_functions[] = {
    {(char *) "function_that_takes_foo", (PyCFunction) _wrap_prc_impl_function_that_takes_foo, METH_KEYWORDS|METH_VARARGS, NULL },
    {NULL, NULL, 0, NULL}
};
/* --- classes --- */


PyTypeObject *_PyFILE_Type;
std::map<void*, PyObject*> *_PyFILE_wrapper_registry;

/* --- exceptions --- */


PyTypeObject *Pystd__exception_Type;

/* --- enumerations --- */





PyMODINIT_FUNC
#if defined(__GNUC__) && __GNUC__ >= 4
__attribute__ ((visibility("default")))
#endif
initprc_impl(void)
{
    PyObject *m;
    PyObject *submodule;
    m = Py_InitModule3((char *) "prc_impl", prc_impl_functions, NULL);
    if (m == NULL) {
        return;
    }
    /* Import the 'FILE' class from module '__builtin__ named file' */
    {
        PyObject *module = PyImport_ImportModule((char*) "__builtin__");
        if (module == NULL) {
            return ;
        }
        _PyFILE_Type = (PyTypeObject*) PyObject_GetAttrString(module, (char*) "FILE");

        if (PyErr_Occurred()) PyErr_Clear();
        PyObject *_cobj = PyObject_GetAttrString(module, (char*) "_PyFILE_wrapper_registry");
        if (_cobj == NULL) {
            _PyFILE_wrapper_registry = NULL;
            PyErr_Clear();
        } else {
            _PyFILE_wrapper_registry = reinterpret_cast< std::map<void*, PyObject*> *> (PyCObject_AsVoidPtr (_cobj));
            Py_DECREF(_cobj);
        }
    }
    /* Register the 'std::exception' exception */
    if ((Pystd__exception_Type = (PyTypeObject*) PyErr_NewException((char*)"prc_impl.exception", NULL, NULL)) == NULL) {
        return;
    }
    Py_INCREF((PyObject *) Pystd__exception_Type);
    PyModule_AddObject(m, (char *) "exception", (PyObject *) Pystd__exception_Type);
    submodule = initprc_impl_PRC();
    if (submodule == NULL) {
        return;
    }
    Py_INCREF(submodule);
    PyModule_AddObject(m, (char *) "PRC", submodule);
    submodule = initprc_impl_std();
    if (submodule == NULL) {
        return;
    }
    Py_INCREF(submodule);
    PyModule_AddObject(m, (char *) "std", submodule);
}
